apiVersion: v1
kind: PersistentVolume
metadata:
  name: share-ssh-keys-2
  labels:
    type: nfs-storage
spec:
  storageClassName: nfs
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: n-adx-recall-4
    path: "/data02/hvd_share/ssh"