apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssh-share
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  selector:
    matchLabels:
      type: local