apiVersion: apps/v1
kind: Deployment
metadata:
  name: hvd-trainjob-1
spec:
  selector:
    matchLabels:
      app: hvd-trainjob-1
  replicas: 1
  template:
    metadata:
      labels:
        app: hvd-trainjob-1
    spec:
      containers:
      - name: hvd-trainjob-1
        image: alwaysproblem/adalgohvd
        command: ["/bin/bash","-c"]
        args:
          - "/usr/sbin/sshd -p 23445 && sleep infinity"
        volumeMounts:
        - mountPath: "/root/.ssh"
          name: ssh-vol-3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 23445
      volumes:
        - name: ssh-vol-3
          persistentVolumeClaim:
              claimName: ssh-share-3
      # restartPolicy: OnFailure

