apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssh-share-3
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
  storageClassName: manual
  selector:
    matchLabels:
      type: local-ssh-3