apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  name: tensorflow-mnist
spec:
  # the number of process on a worker
  slotsPerWorker: 8
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: alwaysproblem/adalgohvd:latest
            imagePullPolicy: IfNotPresent
            name: mpi-launcher
            command:
            - /bin/bash
            - -c
            args:
            #TODO: find out mpirun
            # - "mpirun --allow-run-as-root python fashion.py"
            - "sleep 1d;"
            resources:
              request:
                cpu: 1
                memory: 3Gi
              # limits:
              #   cpu: 2
              #   memory: 20Gi
    Worker:
      replicas: 3
      template:
        spec:
          containers:
          - image: alwaysproblem/adalgohvd:latest
            # use local image first.
            imagePullPolicy: IfNotPresent
            name: mpi-worker
            resources:
              request:
                cpu: 1
                memory: 3Gi
              # limits:
              #   cpu: 2
              #   memory: 20Gi
            volumeMounts:
            - mountPath: /data
              name: dataset
            # - mountPath: /models
            #   name: models
          volumes:
          - name: dataset
            nfs:
              server: n-adx-recall-4
              path: /data02
              readOnly: true
          # - name: models
          #   emptyDir: {}