apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tensorboard-pvc
spec:
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
  storageClassName: nfs
  selector:
    matchLabels:
      type: nfs-storage
      app: tensorboard