apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssh-share-4
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
  storageClassName: nfs
  selector:
    matchLabels:
      type: nfs-storage